apiVersion: v1
kind: Service
metadata:
  name: private-nginx-service

spec:
  type: NodePort

  selector:
    app: private-nginx

  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
