persistence:
  enabled: true
  size: 5Gi

podSecurityContext:
  fsGroup: 472

initChownData:
  enabled: false        # <-- ADD THIS LINE

admin:
  existingSecret: "grafana-admin-credentials"
  userKey: admin-user
  passwordKey: admin-password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://my-prometheus-server.default.svc.cluster.local:80
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
