apiVersion: v1
kind: Pod
metadata:
  name: private-nginx-pod
  labels:
    app: private-nginx

spec:
  containers:
  - name: nginx-container
    image: himansid55/docker-task3:3fc9a65287bff5135d34732b2765c7e678e20ed9

    ports:
    - containerPort: 3000

  imagePullSecrets:
  - name: my-docker-secret
